server:
  port: 8400
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zoracxz/spring-cloud-starter.git    # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 924184702@qq.com                                         # git仓库的账号
          password: xzhm.13617319439                                         # git仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 注册中心eurka地址
# 仓库中的配置文件会被转换成web接口，访问可以参照以下的规则：
#  /{application}/{profile}[/{label}]
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties

#svn配置
#server:
#  port: 8400
#
#spring:
#  cloud:
#    config:
#      server:
#        svn:
#          uri: http://192.168.0.6/svn/repo/config-repo
#          username: username
#          password: password
#        default-label: trunk
#  profiles:
#    active: subversion
#  application:
#    name: spring-cloud-config-server
