server:
  port: 9002
spring:
  application:
    name: node02
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#必须配置，为服务实例添加这个 endpoint，用来暴露 endpoints 的
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream